const substitutions = new Map();
substitutions.set('Witness', 'This dude I know');
substitutions.set('Witnesses', 'These dudes I know');
substitutions.set('Allegedly', 'Kinda probably');
substitutions.set('New study', 'Tumblr post');
substitutions.set('New studies', 'Tumblr posts');
substitutions.set('Rebuild', 'Avenge');
substitutions.set('Space', 'Spaaace');
substitutions.set('Google Glass', 'Virtual Boy');
substitutions.set('Smartphone', 'Pokédex');
substitutions.set('Smartphones', 'Pokédex');
substitutions.set('Electric', 'Atomic');
substitutions.set('Senator', 'Elf-lord');
substitutions.set('Senators', 'Elf-lords');
substitutions.set('Car', 'Cat');
substitutions.set('Cars', 'Cats');
substitutions.set('Election', 'Eating contest');
substitutions.set('Elections', 'Eating contests');
substitutions.set('Congressional leader', 'River spirit');
substitutions.set('Congressional leaders', 'River spirits');
substitutions.set('Homeland security', 'Homestar Runner');
substitutions.set('Could not be reached for comment', 'Is guilty and everyone knows it');
substitutions.set('Debate', 'Dance-off');
substitutions.set('Debates', 'Dance-off');
substitutions.set('Self driving', 'Uncontrollably swerving');
substitutions.set('Poll', 'Psychic reading');
substitutions.set('Polls', 'Psychic reading');
substitutions.set('Candidate', 'Airbender');
substitutions.set('Candidates', 'Airbenders');
substitutions.set('Drone', 'Dog');
substitutions.set('Drones', 'Dogs');
substitutions.set('Vows to', 'Probably won\'t');
substitutions.set('At large', 'Very large');
substitutions.set('Successfully', 'Suddenly');
substitutions.set('Expands', 'Physically expands');
substitutions.set('First-degree', 'Friggin\' awful');
substitutions.set('Second-degree', 'Friggin\' awful');
substitutions.set('Third-degree', 'Friggin\' awful');
substitutions.set('An unknown number', 'Like hundreds');
substitutions.set('Front runner', 'Blade runner');
substitutions.set('Global', 'Spherical');
substitutions.set('Years', 'Minutes');
substitutions.set('Year', 'Minute');
//substitutions.set('Minutes', 'Years');
substitutions.set('No indication', 'Lots of signs');
substitutions.set('Urged restraint by', 'Drunkenly egged on');
substitutions.set('Horsepower', 'Tons of horsemeat');
substitutions.set('Gaffe', 'Magic spell');
substitutions.set('Ancient', 'Haunted');
substitutions.set('Star-Studded', 'Blood-soaked');
substitutions.set('Remains to be seen', 'Will never be known');
substitutions.set('Silver bullet', 'Way to kill werewolves');
substitutions.set('Subway system', 'Tunnels I found');
substitutions.set('Surprising', 'Surprising (but not to me)');
substitutions.set('War of words', 'Interplanetary war');
substitutions.set('Tension', 'Sexual tension');
substitutions.set('Tensions', 'Sexual tensions');
substitutions.set('Cautiously optimistic', 'Delusional');
substitutions.set('Doctor Who', 'The Big Bang Theory');
substitutions.set('Win votes', 'Find Pokémon');
substitutions.set('Behind the headlines', 'Beyond the grave');
substitutions.set('Email', 'Poem');
substitutions.set('Emails', 'Poems');
substitutions.set('Facebook Post', 'Poem');
substitutions.set('Facebook Posts', 'Poems');
substitutions.set('Tweet', 'Poem');
substitutions.set('Tweets', 'Poems');
substitutions.set('Facebook CEO', 'This guy');
substitutions.set('Latest', 'Final');
substitutions.set('Disrupt', 'Destroy');
substitutions.set('Meeting', 'Ménage à trois');
substitutions.set('Meetings', 'Ménage à trois');
substitutions.set('Scientists', 'Channing Tatum and his friends');
substitutions.set('You won\'t believe', 'I\'m really sad about');

module.exports = substitutions;
